version: '3.8'

services:

  gymetra-frontend:
    image: quiroga148/gymetra-frontend:latest
    container_name: gymetra-frontend
    restart: always
    ports:
      - "8100:80"
    networks:
      - gymetra-net

  admin-frontend:
    image: quiroga148/gymetra-admin-frontend:latest
    container_name: gymetra-admin-frontend
    restart: always
    ports:
      - "8101:80"
    networks:
      - gymetra-net

networks:
  gymetra-net:
    driver: bridge
