services:
  admin-frontend:
    build: ./frontend/admin-frontend
    ports:
      - "8101:80"
    container_name: develop-admin-frontend

  gymetra-frontend:
    build: ./frontend/gymetra-frontend
    ports:
      - "8100:80"
    container_name: develop-gymetra-frontend
