services:
  admin-frontend:
    build: ./frontend/admin-frontend
    ports:
      - "8101:8101"
    container_name: main-admin-frontend

  gymetra-frontend:
    build: ./frontend/gymetra-frontend
    ports:
      - "8100:80"
    container_name: main-gymetra-frontend
